# Generated by Django 5.1.4 on 2024-12-24 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReactjsBrowser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shakti',
            fields=[
                ('snippet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ReactjsBrowser.snippet')),
                ('created_updated', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('ReactjsBrowser.snippet',),
        ),
    ]
